#!/usr/bin/perl

$installPath = $ARGV[0];
$UnityVersion = $ARGV[1];

if ($UnityVersion eq 'Unity3') {
	$Unity3 = 1;
} else {
	$Unity3 = 0;
}

$currDir = `pwd`;
chomp $currDir;
$python_script_path = $currDir."/Assets/Plugins/CraftAR-iOS/iOSSetup.py";
$log_filename = "IOSBuildLogFile.txt";

open (LOGFILE, ">$log_filename");
my $perl_v = $];
my $python_v = `python --version 2>&1`;
chomp $python_v;
$debug_info = <<END;
In PostBuildIOSScript
---------------------------
Perl Version: $perl_v
Python Version: $python_v
Unity version: $UnityVersion
Unity 3?: $Unity3
Install Path: $installPath
Current Dir: $currDir
Python Script Path: $python_script_path
Starting python script...
---------------------------\n
END
print LOGFILE $debug_info;
close LOGFILE;

# unzip the SDK, always, in case it has been updated
`unzip -u -o \"$currDir/Assets/Plugins/CraftAR-iOS/CraftARSDK-iOS.zip\" -d \"$currDir/Assets/Plugins/CraftAR-iOS/.libs/\" >> \"$currDir/$log_filename\"`;

# add the necessary libraries to the xcode project
`python \'$python_script_path' \'$installPath\' \'$currDir\'`;

`sed -i -e 's/.*IPHONEOS_DEPLOYMENT_TARGET.*/IPHONEOS_DEPLOYMENT_TARGET = 9.0;/g' \'$installPath\'/Unity-iPhone.xcodeproj/project.pbxproj 2>&1 >>$log_filename`;
`sed -i -e 's|.*FRAMEWORK_SEARCH_PATHS = ".*|FRAMEWORK_SEARCH_PATHS = "../Assets/Plugins/CraftAR-iOS/.libs/";|g' \'$installPath\'/Unity-iPhone.xcodeproj/project.pbxproj 2>&1 >>$log_filename`;

open(LOGFILE, ">>$log_filename");
print LOGFILE "\nBack in PostBuildIOSScript\n";
print LOGFILE "---------------------------\n";
close (LOGFILE);

